--- 创建数据库

CREATE DATABASE weibo;
USER weibo;

--- 创建表

CREATE TABLE USER(
    UID BIGINT PRIMARYKEY AUTO_INCREAMENT,
    NAME CHAR(10) NOT NULL,
    SEX CHAR(1) NOT NULL,
    BYEAR INT NOT NULL,
    CITY CHAR(10) NOT NULL,

    CHECK(SEX = '男' OR SEX = '女')
)
DEFAULT CHARACTER SET UTF8,
AUTO_INCREAMENT = 0;

CREATE TABLE LABEL(
    LID BIGINT PRIMARYKEY AUTO_INCREAMENT,
    LNAME CHAR(10) NOT NULL,
)
DEFAULT CHARACTER SET UTF8,
AUTO_INCREAMENT = 0;


CREATE TABLE MBLOG(
    BID BIGINT PRIMARYKEY AUTO_INCREAMENT,
    TITLE CHAR(10) NOT NULL,
    UID BIGINT NOT NULL,
    PYEAR INT NOT NULL,
    PMONTH INT NOT NULL,
    PDAY INT NOT NULL,
    CONT CHAR(100) NOT NULL,

    ADD CONSTRAINT FK_MBLOG_UID FOREIGN KEY (UID) REFERENCES USER(UID)
)
DEFAULT CHARACTER SET UTF8,
AUTO_INCREAMENT = 0;

CREATE TABLE B_L(
    BID BIGINT NOT NULL,
    UID BIGINT NOT NULL,

    ADD CONSTRAINT FK_B_L_BID FOREIGN KEY (BID) REFERENCES MBLOG(BID),
    ADD CONSTRAINT FK_B_L_UID FOREIGN KEY (UID) REFERENCES USER(UID)
)
DEFAULT CHARACTER SET UTF8,
AUTO_INCREAMENT = 0;

CREATE TABLE FOLLOW(
    UID BIGINT NOT NULL,
    UIDFLED BIGINT NOT NULL,

    ADD CONSTRAINT FK_FOLLOW_UID FOREIGN KEY (UID) REFERENCES USER(UID),
    ADD CONSTRAINT FK_FOLLOW_UIDFLED FOREIGN KEY (UIDFLED) REFERENCES USER(UID)
)
DEFAULT CHARACTER SET UTF8,
AUTO_INCREAMENT = 0;


CREATE TABLE FRIENDS(
    UID BIGINT NOT NULL,
    FUID BIGINT NOT NULL,

    ADD CONSTRAINT FK_FRIENDS_UID FOREIGN KEY (UID) REFERENCES USER(UID),
    ADD CONSTRAINT FK_FRIENDS_FUID FOREIGN KEY (FUID) REFERENCES USER(UID)  
)
DEFAULT CHARACTER SET UTF8,
AUTO_INCREAMENT = 0;

CREATE TABLE SUB(
    UID BIGINT NOT NULL,
    LID BIGINT NOT NULL,
    
    ADD CONSTRAINT FK_SUB_UID FOREIGN KEY (UID) REFERENCES USER(UID),
    ADD CONSTRAINT FK_SUB_LID FOREIGN KEY (LID) REFERENCES LABEL(LID)         
)
DEFAULT CHARACTER SET UTF8,
AUTO_INCREAMENT = 0;

CREATE TABLE THUME(
    UID BIGINT NOT NULL,
    BID BIGINT NOT NULL,

    ADD CONSTRAINT FK_THUME_UID FOREIGN KEY (UID) REFERENCES USER(UID),
    ADD CONSTRAINT FK_THUME_LID FOREIGN KEY (BID) REFERENCES MBLOG(BID)             
)
DEFAULT CHARACTER SET UTF8,
AUTO_INCREAMENT = 0;

CREATE TABLE TOPDAY(
    TYEAR INT NOT NULL,
    TMONTY INT NOT NULL,
    TDAY INT NOT NULL,
    BID INT NOT NULL,
    TNO INT NOT NULL,

    ADD CONSTRAINT FK_TOPDAY_UID FOREIGN KEY (UID) REFERENCES MBLOG(BID),
    CHECK(TNO >= 1 AND TNO <= 10)    
)
DEFAULT CHARACTER SET UTF8,
AUTO_INCREAMENT = 0;

